//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUATCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUATCHIEU()
        {
            this.VEXEMPHIMs = new HashSet<VEXEMPHIM>();
            this.TRANGTHIETBIs = new HashSet<TRANGTHIETBI>();
        }
    
        public int id { get; set; }
        public string MaSuatChieu { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public System.TimeSpan ThoiGianBatDau { get; set; }
        public System.TimeSpan ThoiGianKetThuc { get; set; }
        public int MaPhim { get; set; }
        public int MaPhong { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual PHONG PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEXEMPHIM> VEXEMPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHIETBI> TRANGTHIETBIs { get; set; }
    }
}
