USE DB_LOTTECINEMA

GO
-- TAO PHONG
CREATE PROC TAOPHONG
	@TenPhong NVARCHAR(50)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			INSERT INTO PHONG(TenPhong) VALUES(@TenPhong)
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @MsgError NVARCHAR(2000)
		SELECT @MsgError = N'Lỗi' + ERROR_MESSAGE()
		RAISERROR(@MsgError, 16, 1)
		ROLLBACK TRAN
	END CATCH
END

GO
-- CAP NHAT PHONG
ALTER PROC CAPNHATPHONG
	@MaPhong VARCHAR(9), @TenPhong NVARCHAR(50)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF NOT EXISTS (SELECT * FROM PHONG WHERE MaPhong=@MaPhong)
				RAISERROR(N'Không tìm thấy mã phòng', 16, 1)

			UPDATE PHONG
			SET TenPhong=ISNULL(@TenPhong, TenPhong)
			WHERE MaPhong=@MaPhong
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @MsgError NVARCHAR(2000)
		SELECT @MsgError = N'Lỗi' + ERROR_MESSAGE()
		RAISERROR(@MsgError, 16, 1)
		ROLLBACK TRAN
	END CATCH
END

GO
-- LAY DANH SACH PHONG
CREATE PROC LAYDANHSACHPHONG
AS
BEGIN
	BEGIN TRAN
		SELECT * FROM PHONG
	COMMIT TRAN
END

GO
-- LAY PHONG THEO MA
CREATE PROC LAYPHONGTHEOMA
	@MaPhong VARCHAR(9)
AS
BEGIN
	BEGIN TRAN
		SELECT * FROM PHONG WHERE MaPhong=@MaPhong
	COMMIT TRAN
END

CREATE PROC LAYPHONGTHEOID
	@MaPhong int
AS
BEGIN
	BEGIN TRAN
		SELECT * FROM PHONG WHERE id=@MaPhong
	COMMIT TRAN
END