USE DB_LOTTECINEMA

GO
-- TAO TRANG THIET BI
CREATE PROC TAOTRANGTHIETBI
	@TenThietBi NVARCHAR(200), @TienPhuThem int
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			INSERT INTO TRANGTHIETBI(TenThietBi, TienPhuThem)
			VALUES(@TienPhuThem, @TienPhuThem)
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg NVARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16, 1)
		ROLLBACK TRAN
	END CATCH
END

GO
-- CAP NHAT TRANG THIET BI
CREATE PROC CAPNHATTRANGTHIETBI
	@MaThietBi VARCHAR(11),
	@TenThietBi NVARCHAR(200),
	@TienPhuThem int
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF NOT EXISTS (SELECT * FROM TRANGTHIETBI WHERE MaThietBi=@MaThietBi)
				RAISERROR(N'Không tìm thấy trang thiết bị', 16, 1)

			UPDATE TRANGTHIETBI
			SET TenThietBi=ISNULL(@TenThietBi, TenThietBi),
				TienPhuThem=ISNULL(@TienPhuThem, TienPhuThem)
			WHERE MaThietBi=@MaThietBi
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg NVARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16, 1)
		ROLLBACK TRAN
	END CATCH
END

GO
-- LAY DS TRANG THIET BI
CREATE PROC LAYDSTRANGTHIETBI
AS
BEGIN
	BEGIN TRAN
		SELECT * FROM TRANGTHIETBI
	COMMIT TRAN
END

GO
-- LAY TRANG THIET BI THEO MA
CREATE PROC LAYTRANGTHIETBITHEOMA
	@MaThietBi VARCHAR(11)
AS
BEGIN
	BEGIN TRAN
		SELECT * FROM TRANGTHIETBI WHERE MaThietBi=@MaThietBi
	COMMIT TRAN
END