USE DB_LOTTECINEMA

-----------------------------------
------------SUAT CHIEU---------------
GO
-- LAY DANH SACH SUAT CHIEU
CREATE PROC LAYDSSUATCHIEU
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			SELECT * FROM SUATCHIEU
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
	END CATCH
END

GO
-- LAY SUAT CHIEU THEO MA
ALTER PROC LAYSUATCHIEUTHEOMA
	@MaSuatChieu NVARCHAR(15)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			SELECT * FROM SUATCHIEU WHERE MaSuatChieu=@MaSuatChieu
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
	END CATCH
END

GO
--Tạo kiểu dữ liệu mới lưu danh sách chi tiết thiết bị cho suất chiếu
CREATE TYPE DS_THIETBI AS TABLE
(
	MaThieuBi int
)

GO
-- TAO SUAT CHIEU PHIM
CREATE PROC TAOSUATCHIEU
	@NgayChieu DATE, @ThoiGianBatDau TIME(7), @ThoiGianKetThuc TIME(7), @MaPhim VARCHAR(10), @MaPhong VARCHAR(9), @DS_THIETBI AS DS_THIETBI READONLY
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF NOT EXISTS (SELECT * FROM PHIM WHERE MaPhim=@MaPhim)
			BEGIN
				RAISERROR(N'Không tìm thấy phim', 16, 1)
			END
			IF NOT EXISTS (SELECT * FROM PHONG WHERE MaPhong=@MaPhong)
			BEGIN
				RAISERROR(N'Không tìm thấy phòng', 16, 1)
			END

			INSERT INTO SUATCHIEU VALUES(@NgayChieu, @ThoiGianBatDau, @ThoiGianKetThuc, @MaPhim, @MaPhong)
			
			DECLARE @IdSuatChieu INT = SCOPE_IDENTITY()
			INSERT INTO CHITIETSUATCHIEU_THIETBI(MaSuatChieu, MaThietBi) SELECT @IdSuatChieu, * FROM @DS_THIETBI
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
	END CATCH
END

GO
-- TRA CUU SUAT CHIEU
CREATE PROC TRACUUSUATCHIEU
AS
BEGIN
	RETURN
END