USE DB_LOTTECINEMA

--------------------------------------
----------------THONGKE---------------

GO
-- THONG KE VE BAN RA THEO PHIM
CREATE PROC THONGKE_VEBANRATHEOPHIM
	@NgayBatDau DATE,
	@NgayKetThuc DATE
AS
BEGIN
	BEGIN TRAN
		SELECT P.MaPhim, P.TenPhim, COUNT(*) FROM VEXEMPHIM V
		INNER JOIN SUATCHIEU SC
		ON V.TinhTrang=N'DA_MUA' AND V.MaSuatChieu=SC.id
		INNER JOIN PHIM P
		ON SC.MaPhim=P.id
		GROUP BY P.MaPhim, P.TenPhim
	COMMIT TRAN
END

-- THONG KE SO LUONG HUY DAT CHO THEO PHIM
CREATE PROC THONGKE_VEHUYTHEOPHIM
	@NgayBatDau DATE,
	@NgayKetThuc DATE
AS
BEGIN
	BEGIN TRAN
		SELECT P.MaPhim, P.TenPhim, COUNT(*) FROM VEXEMPHIM V
		INNER JOIN SUATCHIEU SC
		ON V.TinhTrang=N'DA_HUY' AND V.MaSuatChieu=SC.id
		INNER JOIN PHIM P
		ON SC.MaPhim=P.id
		GROUP BY P.MaPhim, P.TenPhim
	COMMIT TRAN
END