USE DB_LOTTECINEMA

----------------------------------------------
-------------------THAMSO---------------------

GO
-- CAP NHAT GIA VE CO BAN
ALTER PROC CAPNHATGIAVECOBAN
	@GiaVeMoi int
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			UPDATE BANGTHAMSO
			SET GiaTri=CONVERT(CHAR(20),@GiaVeMoi)
			WHERE TenThamSo='GIA_VE_CO_BAN'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @MsgError NVARCHAR(2000)
		SELECT @MsgError = N'Lỗi ' + ERROR_MESSAGE()
		RAISERROR(@MsgError, 16, 1)
		ROLLBACK TRAN
	END CATCH
END

--CAP NHAT PHU THU CHO NGOI DEP
CREATE PROC CAPNHATPHUTHUCHONGOIDEP
	@PhuThuMoi int
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			UPDATE BANGTHAMSO
			SET GiaTri=CONVERT(CHAR(20),@PhuThuMoi)
			WHERE TenThamSo='TIEN_PHU_CHO_NGOI_DEP'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		DECLARE @MsgError NVARCHAR(2000)
		SELECT @MsgError = N'Lỗi ' + ERROR_MESSAGE()
		RAISERROR(@MsgError, 16, 1)
		ROLLBACK TRAN
	END CATCH
END